apiVersion: v1
kind: Service
metadata:
  name: chaindeck-api-service
spec:
  selector:
    app: chaindeck-api
  ports:
    - protocol: TCP
      port: 3030
      targetPort: 3030
  type: LoadBalancer
