# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: clickhouse-deployment
# spec:
#   replicas: 1 
#   selector:
#     matchLabels:
#       app: clickhouse
#   template:
#     metadata:
#       labels:
#         app: clickhouse
#     spec:
#       containers:
#       - name: clickhouse
#         image: yandex/clickhouse-server
#         ports:
#         - containerPort: 8123  # ClickHouse HTTP port
#         - containerPort: 9000  # ClickHouse native port
#         # Add other configuration options if needed


apiVersion: apps/v1
kind: Deployment
metadata:
  name: clickhouse-db
  labels:
    app: clickhouse-db
spec:
  replicas: 2
  selector:
    matchLabels:
      app: clickhouse-db
  template:
    metadata:
      labels:
        app: clickhouse-db
    spec:
      containers:
        - name: clickhouse-server
          image: yandex/clickhouse-server:latest
          ports:
            - containerPort: 9000
          volumeMounts:
            - name: config-volume
              mountPath: /etc/clickhouse-server/config.d
        - name: clickhouse-client
          image: yandex/clickhouse-client:latest
          command: ["tail", "-f", "/dev/null"]
      volumes:
        - name: config-volume
          configMap:
            name: clickhouse-config
            defaultMode: 0644

